name: Deploy ToDo app

on:
  push:
    branches: [main]
    pull_request: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.x, 8.x]
    steps:
      - uses: action/checkout@v3
        with:
          php-version: ${{matrix.php-version}}
      -name: Install Composer Dependencies
      working-directory: ./
      -run: composer install --prefer-dist
      -name: Run Tests
      working-directory: ./
      -run: ./vendor/bin/phpunit --verbose tests
