name: Deploy ToDo app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.x, 8.x]

    steps:
    - uses: actions/checkout@v3
    - name: Install Composer Dependencies
    - run: composer install --prefer-dist
