name: Deploy ToDo app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.x, 8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Composer Dependencies
      uses: actions/setup-php@v1
      with:
        node-version: ${{ matrix.php-version }}
      working-directory: ./
    - run: composer install --prefer-dist
    - name: Run Tests
      working-directory: ./
    - run: ./vendor/bin/phpunit --verbose tests
